// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Whatsapp_API.Data;

#nullable disable

namespace Whatsapp_API.Data.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20251021231435_AddAgentRequestedAtToConversations_V4")]
    partial class AddAgentRequestedAtToConversations_V4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Whatsapp_API.Models.Entidades.Mensajeria.Adjunto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Data")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("data");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int")
                        .HasColumnName("empresa_id");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file_name");

                    b.Property<int>("MessageId")
                        .HasColumnType("int")
                        .HasColumnName("message_id");

                    b.Property<string>("MimeType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mime_type");

                    b.Property<DateTime?>("UploadedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("attachments");
                });

            modelBuilder.Entity("Whatsapp_API.Models.Entidades.Mensajeria.Contacto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("country");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int")
                        .HasColumnName("empresa_id");

                    b.Property<double?>("LastLocationLatitude")
                        .HasColumnType("float")
                        .HasColumnName("last_location_latitude");

                    b.Property<double?>("LastLocationLongitude")
                        .HasColumnType("float")
                        .HasColumnName("last_location_longitude");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_message_at");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<bool>("WelcomeSent")
                        .HasColumnType("bit")
                        .HasColumnName("welcome_sent");

                    b.HasKey("Id");

                    b.ToTable("contacts");
                });

            modelBuilder.Entity("Whatsapp_API.Models.Entidades.Mensajeria.Conversacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AgentRequestedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("agent_requested_at");

                    b.Property<int>("AiMessages")
                        .HasColumnType("int")
                        .HasColumnName("ai_messages");

                    b.Property<int?>("ClosedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("closed_by_user_id");

                    b.Property<int>("ContactId")
                        .HasColumnType("int")
                        .HasColumnName("contact_id");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int")
                        .HasColumnName("empresa_id");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ended_at");

                    b.Property<int?>("FirstResponseTime")
                        .HasColumnType("int")
                        .HasColumnName("first_response_time");

                    b.Property<bool>("GreetingSent")
                        .HasColumnType("bit")
                        .HasColumnName("greeting_sent");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_activity_at");

                    b.Property<int?>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<int>("TotalMessages")
                        .HasColumnType("int")
                        .HasColumnName("total_messages");

                    b.HasKey("Id");

                    b.HasIndex("ClosedByUserId", "EndedAt");

                    b.HasIndex("ContactId", "StartedAt");

                    b.HasIndex("EmpresaId", "AgentRequestedAt");

                    b.ToTable("conversations");
                });

            modelBuilder.Entity("Whatsapp_API.Models.Entidades.Mensajeria.Mensaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContactId")
                        .HasColumnType("int")
                        .HasColumnName("contact_id");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int")
                        .HasColumnName("conversation_id");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int")
                        .HasColumnName("empresa_id");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10,6)")
                        .HasColumnName("latitude");

                    b.Property<string>("LocationName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("location_name");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(10,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sender");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("sent_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("ConversationId", "SentAt");

                    b.ToTable("messages");
                });

            modelBuilder.Entity("Whatsapp_API.Models.Entidades.Seguridad.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("profiles");
                });

            modelBuilder.Entity("Whatsapp_API.Models.Entidades.Seguridad.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarFileName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("avatar_file_name");

                    b.Property<string>("AvatarMimeType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("avatar_mime_type");

                    b.Property<DateTime?>("AvatarUpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("avatar_updated_at");

                    b.Property<int?>("ContactId")
                        .HasColumnType("int")
                        .HasColumnName("contact_id");

                    b.Property<int>("ConversationCount")
                        .HasColumnType("int")
                        .HasColumnName("conversation_count");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("correo");

                    b.Property<string>("Empresa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("empresa");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("int")
                        .HasColumnName("empresa_id");

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.Property<int?>("IdPerfil")
                        .HasColumnType("int")
                        .HasColumnName("idPerfil");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit")
                        .HasColumnName("is_online");

                    b.Property<DateTime?>("LastActivity")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_activity");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_login");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.Property<string>("Pass")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pass");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("Whatsapp_API.Models.Entidades.Sistema.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FlowKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("empresas");
                });

            modelBuilder.Entity("Whatsapp_API.Models.Entidades.Sistema.Integracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("AccessTokenEnc")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("access_token_enc");

                    b.Property<string>("ApiBaseUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("api_base_url");

                    b.Property<string>("ApiVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("api_version");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int")
                        .HasColumnName("empresa_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("PhoneNumberId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone_number_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("provider");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("VerifyTokenHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("verify_token_hash");

                    b.Property<string>("WabaId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("waba_id");

                    b.HasKey("Id");

                    b.ToTable("integrations");
                });

            modelBuilder.Entity("Whatsapp_API.Models.Entidades.Sistema.WhatsappTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BodyParamCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TemplateIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Name", "Language")
                        .IsUnique();

                    b.ToTable("WhatsappTemplates");
                });

            modelBuilder.Entity("Whatsapp_API.Models.Entidades.Mensajeria.Adjunto", b =>
                {
                    b.HasOne("Whatsapp_API.Models.Entidades.Mensajeria.Mensaje", "Mensaje")
                        .WithMany("Adjuntos")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mensaje");
                });

            modelBuilder.Entity("Whatsapp_API.Models.Entidades.Mensajeria.Conversacion", b =>
                {
                    b.HasOne("Whatsapp_API.Models.Entidades.Seguridad.Usuario", "ClosedByUser")
                        .WithMany()
                        .HasForeignKey("ClosedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Whatsapp_API.Models.Entidades.Mensajeria.Contacto", "Contacto")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClosedByUser");

                    b.Navigation("Contacto");
                });

            modelBuilder.Entity("Whatsapp_API.Models.Entidades.Mensajeria.Mensaje", b =>
                {
                    b.HasOne("Whatsapp_API.Models.Entidades.Mensajeria.Contacto", "Contacto")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Whatsapp_API.Models.Entidades.Mensajeria.Conversacion", "Conversacion")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contacto");

                    b.Navigation("Conversacion");
                });

            modelBuilder.Entity("Whatsapp_API.Models.Entidades.Mensajeria.Mensaje", b =>
                {
                    b.Navigation("Adjuntos");
                });
#pragma warning restore 612, 618
        }
    }
}
